
image:
  file: .gitpod.dockerfile

tasks:
  - command: redis-server
  - init: bin/setup
    command: bin/rails s -p 3000
  - init: bin/setup
    command: bin/rails tailwindcss:watch
    # command: bin/dev

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port: 6379
    onOpen: ignore
  - port: 443
    onOpen: ignore

vscode:
  extensions:
    - vscodevim.vim

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
