# custom image since we use redis
image:
  file: .gitpod.dockerfile

tasks:
  - command: redis-server
  - init: bin/setup
    command: bin/rails s -p 3000
  - init: bin/setup
    command: bin/rails tailwindcss:watch
    # command: bin/dev
  - name: Bash
    before: echo hi $USER, now is `date`
    init: pwd
    command: ls

ports:
  # rails
  - port: 3000
    onOpen: open-preview
  # redis
  - port: 6379
    onOpen: ignore

vscode:
  extensions:
    - vscodevim.vim
